### ISSUE TITLE
`mr-jenk` | Add Jenkins pipeline

### ISSUE THREAD

**Issue by maximihajlov** [merpw/lets-play#22]
This issue is a place to discuss the `mr-jenk` task.

## [Task description and audit questions](https://github.com/01-edu/public/tree/master/subjects/java/projects/mr-jenk)

- [x] Initialize Jenkins using Docker

- [x] Implement a simple pipeline to automatically run tests

- [x] Improve the pipeline to build docker images

- [x] Implement test reports

- [x] Add email notifications

- [ ] Add automatic deployments

- [ ] Implement rollback strategy for deployments

**Comment by maximihajlov** [comment]
Jenkins is up and running at [jenkins.mer.pw](https://jenkins.mer.pw/)

**Comment by maximihajlov** [comment]
Due to complexity of the project and high resource usage, the deployed Jenkins instance is not reliable enough to be used in production. Even with 2vCPU+4GB RAM server the instance it takes more than 10 minutes to test and build the project. It can be fixed by using destributed builds, but it will add additional complexity, which is not desired for this project. 

As we already have GH Actions pipelines, it makes more sense to the local instance of Jenkins as a Proof-of-Concept and to submit the task. 

The checklist was updated.

**Comment by maximihajlov** [comment]
### Audit checklist

#### Functional

##### Download the project and trigger a Jenkins build. Observe if the pipeline runs as expected.

- [ ] Does the pipeline initiate and run successfully from start to finish?

##### Trigger some intentional build errors and observe Jenkins' response.

- [ ] Does Jenkins respond appropriately to build errors?

##### Examine the automated testing step.

- [ ] Are tests run automatically during the pipeline execution? Does the pipeline halt on test failure?

##### Make a minor change in the source code, commit, and push. Observe if the pipeline is triggered automatically.

- [ ] Does a new commit and push automatically trigger the Jenkins pipeline?

##### Check the deployment process.

- [ ] Is the application deployed automatically after a successful build? Is there a rollback strategy in place?

#### Security

##### Examine the permissions on the Jenkins dashboard.

- [ ] Are permissions set appropriately to prevent unauthorized access or changes?

##### Review how sensitive data (like API keys, passwords) is managed in Jenkins.

- [ ] Is sensitive data secured using Jenkins secrets or environment variables?

#### Code Quality and Standards

##### Examine the Jenkinsfile or the build configuration.

- [ ] Is the code/script well-organized and understandable? Are there any best practices being ignored?

##### Look into the test report formats and outputs.

- [ ] Are test reports clear, comprehensive, and stored for future reference?

##### Check for notifications setup.

- [ ] Are notifications triggered on build and deployment events? Are they informative?

#### Bonus

##### Examine if parameterized builds are implemented.

- [ ] +Are there options for customizing the build run with different parameters?

##### Examine the distributed builds (if implemented).

- [ ] +Are multiple agents utilized effectively for distributed builds?
