### ISSUE TITLE
buy-02 CI/CD checklist

### ISSUE THREAD

**Issue by adrian-lui** [merpw/lets-play#40]
This issue will be looked into during the project together.
Some of these issues are depending on mr-jenk and safe-zone projects.

- [ ] Ensure best practices in collaborative development process with PRs and reviews.
- [ ] Use CI/CD pipeline to automatically build, test, and deploy PRs (with Jenkins or GH, TBC)
- [ ] Utilize SonarQube to ensure code quality and adherence to best practices.
- [ ] Proper documentation of the new features.
- [ ] Ensure unit testing in both frontend and backend
